### ISSUE TITLE
Restore original license and copyright notice

### ISSUE THREAD

**Issue by tfmorris** [zepheira/exhibit3#105]
The original 2006 MIT copyright notice & license appears to be missing.

http://code.google.com/p/simile-widgets/source/browse/exhibit/trunk/LICENSE.txt

One of the requirements of that license is that they copyright notice be preserved in both source and binary distributions.

**Comment by zepheiryan** [comment]
The license is in the root directory, https://github.com/zepheira/exhibit3/blob/master/LICENSE.txt

**Comment by tfmorris** [comment]
@zepheiryan Thanks for following up on this, but that appears to be a different license and copyright notice than I linked to in the original issue (and which is included in the original source code).

Obviously the requirement only applies to code that you derived from the original project, not new code written from scratch, but it would appear that a substantial amount of code falls into the former category.  There's no issue with adding new (compatible) licenses and copyright notices, but you can't legally remove the required ones.

**Comment by zepheiryan** [comment]
Thanks, you're totally right.  I've brought it back as https://github.com/zepheira/exhibit3/blob/master/ORIGINAL-LICENSE.txt in both active branches.
