### ISSUE TITLE
Multi-Term-Query for Text Search Facet

### ISSUE THREAD

**Issue by ewomant** [zepheira/exhibit3#106]
Hello everybody,

recently I noticed, that the text search facet treats queries as a single string. The resulting behaviour is in contrast to most common text search functions and dialogues. 

In [this example at simile-widgets.org](http://www.simile-widgets.org/exhibit3/examples/senate/senate.html),  a query on "Committee Indian" would not return any results, while "Committee on Indian" returns 14 Senators. _(To try it out, you will have to copy the query-string into the search field, entering the query using the keyboard is prohibited because each "space" entered will be removed during input.)_ 

Expected results in many cases would be to return all items, where both "committee" AND "indian" appears somewhere in the item. Of course, there are multiple options here, e.g. an logical OR-Operator or searches on a single field. But to implement this in a flexible and scalable way probably requires server-side search infrastructure.

To work around this issue, I have prepared a a proposal for a simple function, which **splits a query at each space-character, searches each document for the appearance of each query-string and combines the results using a logical "AND"-operator**. 

Basically, only the 'restrict '-function in 'text-search-facet.js' has to be altered. **In addition, several ".trim()" statements have to be removed (or made optional) at various points to allow for the input of trailing spaces.** This could be considered as an additional option for the text search facet.

This is the proposed 'restrict'-function for Exhibit.TextSearchFacet  ('text-search-facet.js') in Exhibit 3:

``` javascript
Exhibit.TextSearchFacet.prototype.restrict = function(items) {
    var set, itemToValue, text;

    if ((this._text === null) || (jQuery.trim(this._text) === "")) {
        return items;
    } else {
        Exhibit.jQuery(this.getContainer()).trigger("onTextSearchFacetSearch.exhibit", [this._text]);
        this._buildMaps();

        set = new Exhibit.Set();
        itemToValue = this._itemToValue;
        text = this._text.toLowerCase().trim(); //trimming is now performed here, so the query itself is not altered

        var terms = text.split(" ");        //split query
        //TODO: clean junk, eg. , . &

                if (terms.length > 0) {
            //iterate documents
            items.visit(function(item) {
                var values;
                var countTerms = 0;
                var hit = true;
                if ( typeof itemToValue[item] !== "undefined") {
                    values = itemToValue[item];
                    var itemtext = values.join(" ");
                    while (countTerms < terms.length && hit) {//& hit = true
                        var term = Exhibit.jQuery.trim(terms[countTerms]);
                        hit = (term !== "" && itemtext.indexOf(term) >= 0);
                        countTerms++;
                    }   
                }
                if (hit) {
                    set.add(item);
                }
            });
        }
        return set;
    }
};
```

The additional search operations didn't have a noticeable impact on response time with my collection consisting of 150 elements. Of course, this will depend largely on query length and collection size.

What is still missing is to add an option to the facet to select the query-mode, so current installations will not be altered. I don't really know how to do this, and how to proceed to bring the code into a pull-request on git. Any hints and help on this will be appreciated. 

In practice it should be sufficient to make the trimming of the query and the split-operation dependent on a new option "multiTermAnd", which can be set to 'false' as default.

Thanks to everybody for this great project, which I use to build prototypes of faceted search interfaces.

Ben

**Comment by karger** [comment]
Thanks for this contribution; I agree with your analysis and proposed fixed.  However, I don't understand your point about adding an option to the facet to select the query mode.  Is your concern that some people have come to rely on the "exact match" functionality?  My initial assumption is that nobody is relying on this, for the reason you gave---that everyone knows the default in text search is "AND".  So, I'd like to take your change as is.

We've shifted further development of exhibit3 to a new repo managed by the simile-widgets team, at https://github.com/simile-widgets/exhibit .  If you can prepare a pull request with this change, I believe our committers will quickly incorporate it.

**Comment by ewomant** [comment]
Thanks for your reply. Yes, I would have cautiously assumed that some installations might rely on this behavior - even though  I would have no idea, why exactly...  And thanks for the hint towards the new repository, I had not noticed the switch. I will prepare a pull request there.
