### ISSUE TITLE
dist demos use wrong path

### ISSUE THREAD

**Issue by jjon** [zepheira/exhibit3#107]
After a basic read-only install of exhibit3 scripted, using `git clone git://github.com/zepheira/exhibit3.git` and then `ant dist`, the demos thus created have these  paths for the exhibit scripts:

```
<link rel="exhibit-extension" type="text/javascript" href="../src/extensions/time/time-extension.js?bundle=false" />
<script src="../src/exhibit-api.js?bundle=false"></script>
```

where the source path should be `../../src/`

**Comment by zepheiryan** [comment]
This is corrected in the requirejs branch.  The Jetty server is back and bundled in, so you could just run it and not worry about the paths.  When it's built as a distribution, though, the file refs should be correct, both filesystem and URL-wise.

(This is more of a bookmark for reference; what's on the requirejs branch isn't exactly ready for widespread consumption.)
