### ISSUE TITLE
Edge case for lens template processing in Google Map view

### ISSUE THREAD

**Issue by eroby** [zepheira/exhibit3#108]
The following is a part of a custom lens template (for an image src tag) that is failing in the map view:

  ex:src-content=".thumbnail"

An example of a definition for .thumbnail is -

http://maps.google.com/maps/api/staticmap?center=48.148376300000002,-122.4197436&zoom=2&size=100x100&markers=color:orange%7Clabel:%7C48.148376300000002,-122.4197436&maptype=satellite&sensor=false

When I inspect this element with FireFox Web Tools and 'Copy Outer HTML' it shows the following -

http://maps.google.com/maps/api/staticmap?center=48.148376300000002,-122.4197436&amp;zoom=2&amp;size=100x100&amp;markers=color:orange%7Clabel:%7C48.148376300000002,-122.4197436&amp;maptype=satellite&amp;sensor=false

I use the same definition with both timeline and tabular views - which do not encode '&'  -  and therefore work as expected.

Note that this has become an issue since moving to Exhibit Version 3.0. Also note that this same Map Lens Template displays properly in IE. But I saw in the code where there is a fall-back to Version 2.0 for IE - which was very confusing at first.

I have scoured the source and cannot isolate where this might be happening.

Thanks in advance for any insight.

**Comment by karger** [comment]
Further development of exhibit3 should be happening primarily at https://github.com/simile-widgets/exhibit .  Probably best to post this issue there.

**Comment by karger** [comment]
Also, it is helpful to post a link to a live broken exhibit

**Comment by eroby** [comment]
Thanks David...

**Comment by karger** [comment]
When I inspect your example with firebug on firefox, and look at one of the thumbnails in a pop-up over a map pin, I find that the thumbnail image does in fact have a valid url, but that the height and width attributes are being set to 0.  If you go in and manually set height and width to 100 (which is what they should be, given your lens) the image appears in the bubble.

So there does seem to be something wrong, but not clear it is a problem with the character escapes.

**Comment by eroby** [comment]
I see what you mean.  Now I am even more confused...

**Comment by karger** [comment]
You img ex:src-content has no explicit setting of height and width 
attributes.  why don't you try adding an explicit height=100 width=100 
to the img tag.

**Comment by eroby** [comment]
If you need to hookup to the full data source see

http://clearinghouse.marinedebris.noaa.gov/data-bindings/map-init.csv

**Comment by eroby** [comment]
David-

That did it!!!

Thanks for the HUGE assist.

Cheers,
Eric
