### ISSUE TITLE
Add back cloud facet

### ISSUE THREAD

**Issue by Pike** [zepheira/exhibit3#14]
One of the facets I use myself is the cloud facet.

I wanted to get my feet wet, so I tried a port, like so:

I started off with a three way merge of the exhibit 2 list-facet.js, cloud-facet.js and the 3 list-facet.js. That got me pretty far, then I had to port over import- and exportState and stateDiffers stuff, and replace a bit of SimileAjax. Found that createDOMFromString(...) is now $.simileDOM("string", ...).

I don't know how to really create tests for facets, so I just created a small demo for the cloud facet to check that it does what I expect it to. Not sure if I caught all changes.

**Comment by zepheiryan** [comment]
I brought back automated command line testing yesterday, but we haven't built up tests to the point of doing functional testing on facets yet, so don't worry about that.  Great work, thanks again for your contribution.

**Comment by Pike** [comment]
Thanks. I see that you pulled the thumbnail view, too :-)

**Comment by zepheiryan** [comment]
I noticed there were some lines jslint didn't like and ran the new classes through - there's an undocumented build task I use to help check one file at a time, e.g., `ant lintone -Dlintfile=src/scripts/ui/views/thumbnail-view.js`, and one for checking linting everything, `ant lint`, which gets run under `ant test`.  See 50f8f4e10a62fe23206bb3a7ffcea77bd7bf03be and de069e50364fb957350fdffd1b8c1e05bae879e6
