### ISSUE TITLE
Bug between Exhibit.Backwards.Attributes.getAttribute and Exhibit._Impl.prototype.configureFromDOM

### ISSUE THREAD

**Issue by karger** [zepheira/exhibit3#41]
Exhibit.Backwards.Attributes.getAttribute expects a single DOM element as its first argument.  Instead it is receiving a jquery object and breaking.  The problem starts from

Exhibit._Impl.prototype.configureFromDOM which invokes

panel = Exhibit.ControlPanel.createFromDOM(
$("<div>").prependTo(document.body),
null,
uiContext
); 

the first (jquery object) argument is passed to getConfigurationFromDOM which passes it to Exhibit.Backwards.Attributes.getAttribute  which breaks.

**Comment by zepheiryan** [comment]
I've fixed this locally and will push it after testing.

In the meantime, could you perhaps familiarize yourself with GitHub markup?  I know it's a pain to keep adding these different wiki-esque markups into the mix, but it would have been easier to read your issue if it had the code markup around it.  There should be a cheat sheet popup link above the upper right of every GitHub text entry box.

**Comment by zepheiryan** [comment]
Fixed with 8b08ede604e8c7808cdd9e37e14742bbd8f3469d
