### ISSUE TITLE
non-backward-compatible json parsing

### ISSUE THREAD

**Issue by karger** [zepheira/exhibit3#42]
E2 used eval to parse its exhibit/data files while E3 uses the stricter JSON.Parse.  This will be a source of breakage if people try to switch to using exhibit 3.  For example in E2 property names in the data file need not be quoted while in E3 they must.  Should E3 back-off and try more relaxed parsing if JSON.Parse fails?  If not, there should be an entry about this incompatibility in the E2-->E3 upgrade guide (we have an E2-->E3 upgrade guide, right?)

**Comment by zepheiryan** [comment]
Several places describe and link to the issue in which a solution is offered: https://github.com/zepheira/exhibit3/issues/37

**Comment by karger** [comment]
True backward compatibility would load the invalid-json extension by default, while offering some "strict" option that would cancel the default load.

**Comment by zepheiryan** [comment]
I considered several options, including one similar to your proposal.  But anything involving retaining malformed JSON parsing in core would conflict with #38 and generally conflicts with the goal that users really need to update their data.

I'm not closed to the idea of doing some of this differently - perhaps on parsing errors, Exhibit auto-loads this extension - but whatever the solution is, it shouldn't involve the perception that malformed JSON will continue to work.  At some point, that will break, and now might as well be that time.

**Comment by karger** [comment]
Arguably, the fact that malformed json is slow (has to throw errors and 
be parsed twice) seems like a gentle incentive for people to switch.  
Perhaps we should try that for a while before getting strict?

As a middle-of-the-road option, what if we created a small visual 
indicator---such as a small, non-modal alert---that displayed when 
exhibit encountered a recoverable error (such as invalid json).  
People's exhibits would still work just fine, but they would get a 
"nag" to fix these errors until they did.

**Comment by zepheiryan** [comment]
Properly responding to a JSON library parsing error with an attempt to re-evaluate is probably a negligible performance penalty.  Except in the pathological case where there's a huge amount of data with the defect at the end, I doubt anybody would notice.

We've discussed nagging in the past (as a mechanism to force updating) and discarded it as interfering too much with the author's intentions without their knowledge.  This is something the author needs to catch for themselves.

I am still open to different possibilities, but neither of these strike me as workable alternatives.

**Comment by zepheiryan** [comment]
Actually, I guess that upgrade take on the nag is a sufficiently different scenario to not apply; perhaps that's one possible use of the new control panel feature.

I'm still very much not attracted to the idea of letting bad JSON back into core, though.  I see updating data as one more of the intentional steps required to go from 2 to 3.

**Comment by karger** [comment]
It seems we are prioritizing to shift as many people as possible from E2 to E3.  If that is true, then any incompatibility that deters the shift should be looked at carefully.  Perhaps a good approach would be to automatically tolerate bad JSON in 3.0 (possibly with nag as discussed above), with a plan to remove said tolerance in 3.1?  ie, get people to switch, _then_ make them fix their json.

**Comment by zepheiryan** [comment]
Why delay?  That sounds a bit like make the switch, then make the switch.  I'd rather see that as part of the upgrade path when there's already an association that some steps are necessary going from 2 to 3.

**Comment by karger** [comment]
Instead of make switch then make switch, I would view it as "warn of 
switch, then make switch".  ie 3.0 would warn people about their broken 
js but not fail, while 3.1 would fail.
