### ISSUE TITLE
Add jetty server and examples directory to git repository

### ISSUE THREAD

**Issue by karger** [zepheira/exhibit3#43]
The E2 subversion repository came with a jetty server for the local repository and a subdirectory full of example exhibits.  This made it easy to develop/test exhibit.   Can we create a similar subdirectory in the E3 repository?

**Comment by zepheiryan** [comment]
I am unlikely to work on tasks for features I don't personally find useful.  You are welcome to add this to your fork and present it as a pull request.

Note that the nice but naive connection between version control and distribution has been broken.  Trying to keep developers to the convention of making non-broken commits and also bundling for every new commit is too much protocol, so bundling is now part of the distribution task in ant.  You could still develop out of the `src` directory by making sure you turn bundling off where it pertains.

**Comment by karger** [comment]
Given the sophistication of modern script loaders and http keepalive, 
is bundling still worth it at all?  Have there been any comparisons of 
load times?

**Comment by zepheiryan** [comment]
No performance testing was done on that (open an issue if that's of interest), and perhaps conventional wisdom is wrong (jQuery, etc.), but just about everybody aims to deliver their final product in one compressed file, which intuitively should take less time to transfer than several uncompressed scripts.
