### ISSUE TITLE
Relativize links to exhibit code in demos directory?

### ISSUE THREAD

**Issue by karger** [zepheira/exhibit3#45]
The files in the demos directory currently link to a specific release (http://api.simile-widgets.org/exhibit/3.0.0rc1/exhibit-api.js).  For testing (and futureproofing) would it be better to use relative links to the accompanying scripts in the same repository?  e.g. "../../dist/exhibit-api.js" or "../../src/exhibit-api.js"?  For development purposes, the ideal would probably to link to the src directory with bundle=false, so people can directly test against their changes to the code. The bundles won't be available in src, but that seems less problematic for testers.

**Comment by zepheiryan** [comment]
That was how things were arranged prior to making a release.  It might be time to start drawing a separation between polished demos and development fodder.  They're a bit mixed; one should be stable and pointing at a release for easy copy-paste by interested users, the other should be more malleable and easier for use by developers.

There are some general project changes that should take place, maybe one of them is to split site management (with polished demos) from development entirely.

**Comment by karger** [comment]
I'm not sure I see the drawback in relativizing even for a release.  If 
the demo directory is part of the release, then the relative links 
would point to the released code, right?

**Comment by zepheiryan** [comment]
I'm not sure what you're responding to.  I suggested moving polished demos to a separate repository along with site management and retaining developer fodder, in a way consistent with the relative URLs you suggested / the way it was before a release.

**Comment by karger** [comment]
I agree on having a relative-links set of demos in the development repository.  How do you see the polished-demos repository being managed?   Will it be "compiled" from the development demos in some way?  Will it contain absolute links to the exhibit api?  Where?  At simile-widgets.org/exhibit3?

**Comment by zepheiryan** [comment]
See #78

**Comment by karger** [comment]
OK, you've stated (issue 85) that what needs to be done is "obvious".   But not to me.  I'd be happy to take care of it if you could clarify.
