### ISSUE TITLE
pagination throws errors

### ISSUE THREAD

**Issue by idot** [zepheira/exhibit3#48]
Pagination is broken:
The senate demo, when switching to tiles view throws errors.
Removing the "ex:paginate="true" makes tiles view work again.

The same error happens when I try to paginate my exhibit view.

Uncaught TypeError: Cannot call method 'bind' of undefined
fexhibit-scripted-bundle.js:1
Exhibit.Debug.exceptionexhibit-scripted-bundle.js:1
Exhibit.ViewPanel._createViewexhibit-scripted-bundle.js:1
Exhibit.ViewPanel._switchViewexhibit-scripted-bundle.js:1
Exhibit.ViewPanel.importStateexhibit-scripted-bundle.js:1
Exhibit.History.stateListenerexhibit-scripted-bundle.js:1
f.event.dispatchjquery-1.7.1.min.js:3
f.event.add.h.handle.ijquery-1.7.1.min.js:3
f.event.triggerjquery-1.7.1.min.js:3
f.fn.extend.triggerjquery-1.7.1.min.js:3
e.extend.eachjquery-1.7.1.min.js:2
e.fn.e.eachjquery-1.7.1.min.js:2
f.fn.extend.triggerjquery-1.7.1.min.js:3
c.Adapter.triggerjquery.history.js:1
m.initCore.m.onPopStatejquery.history.js:1
f.event.dispatchjquery-1.7.1.min.js:3
f.event.add.h.handle.ijquery-1.7.1.min.js:3
f.event.triggerjquery-1.7.1.min.js:3
f.fn.extend.triggerjquery-1.7.1.min.js:3
e.extend.eachjquery-1.7.1.min.js:2
e.fn.e.eachjquery-1.7.1.min.js:2
f.fn.extend.triggerjquery-1.7.1.min.js:3
c.Adapter.triggerjquery.history.js:1
m.initCore.m.pushStatejquery.history.js:1
Exhibit.History.pushStateexhibit-scripted-bundle.js:1
Exhibit.History.pushComponentStateexhibit-scripted-bundle.js:1
Exhibit.ViewPanel._selectViewexhibit-scripted-bundle.js:1
(anonymous function)exhibit-scripted-bundle.js:1
dom.setViewIndex.handlerexhibit-scripted-bundle.js:1
f.event.dispatchjquery-1.7.1.min.js:3
f.event.add.h.handle.i

**Comment by zepheiryan** [comment]
This appears to be a broader and more serious problem with generally switching views.  I'll look into it; thanks for the report.

If you're interested in development on Exhibit 3 at all, you might want to try test cases against a checkout that doesn't use bundling.  The stack traces are quite a bit easier to parse.

**Comment by zepheiryan** [comment]
This specific issue should be fixed in trunk by 0814c0b3695bb96e79272c2b00de8b3c17d1f784 (wrong locale key).  There seems to be a more insidious bug around view switching; I'll open a new issue if I can nail it down.
