### ISSUE TITLE
Link error for static files in Tabular View Lens pop-up

### ISSUE THREAD

**Issue by Resseguie** [zepheira/exhibit3#49]
When clicking the link generated for a property of type "Item" in the Tabular View, the generated pop-up to show the linked item details is referencing a number of static image files that can't be found (404):

(From Chrome developer console)
GET http://api.simile-widgets.org/exhibit/images/bubble-top-left.png 404 (Not Found)
GET http://api.simile-widgets.org/exhibit/images/bubble-top-right.png 404 (Not Found)
GET http://api.simile-widgets.org/exhibit/images/bubble-bottom-left.png 404 (Not Found)
GET http://api.simile-widgets.org/exhibit/images/bubble-left.png 404 (Not Found)
GET http://api.simile-widgets.org/exhibit/images/bubble-right.png 404 (Not Found)
GET http://api.simile-widgets.org/exhibit/images/bubble-bottom-right.png 404 (Not Found)
GET http://api.simile-widgets.org/exhibit/images/bubble-top.png 404 (Not Found)
GET http://api.simile-widgets.org/exhibit/images/close-button.png 404 (Not Found)
GET http://api.simile-widgets.org/exhibit/images/bubble-arrow-point-down.png 404 (Not Found)
GET http://api.simile-widgets.org/exhibit/images/bubble-bottom.png 404 (Not Found)

There is then no way to close the "naked" pop-up window without refreshing the page. You get the same behavior with the default lens for a linked item and a custom lens (div[ex:role="lens]) defined within the table view

**Comment by expectationlost** [comment]
+1 when referring to http://api.simile-widgets.org/exhibit/3.0.0rc1/exhibit-api.js its looking for those images files

bubble-top-left.png:1GET http://api.simile-widgets.org/exhibit/images/bubble-top-left.png 404 (Not Found)
bubble-top-right.png:1GET http://api.simile-widgets.org/exhibit/images/bubble-top-right.png 404 (Not Found)
bubble-bottom-left.png:1GET http://api.simile-widgets.org/exhibit/images/bubble-bottom-left.png 404 (Not Found)
bubble-bottom-right.png:1GET http://api.simile-widgets.org/exhibit/images/bubble-bottom-right.png 404 (Not Found)
bubble-left.png:1GET http://api.simile-widgets.org/exhibit/images/bubble-left.png 404 (Not Found)
bubble-right.png:1GET http://api.simile-widgets.org/exhibit/images/bubble-right.png 404 (Not Found)
bubble-top.png:1GET http://api.simile-widgets.org/exhibit/images/bubble-top.png 404 (Not Found)
bubble-bottom.png:1GET http://api.simile-widgets.org/exhibit/images/bubble-bottom.png 404 (Not Found)
close-button.png:1GET http://api.simile-widgets.org/exhibit/images/close-button.png 404 (Not Found)
bubble-arrow-point-down.png:1GET http://api.simile-widgets.org/exhibit/images/bubble-arrow-point-down.png 404 (Not Found)

**Comment by zepheiryan** [comment]
This is because the bundled CSS is installed in a directory different from the individual, unbundled CSS, so the paths to the images end up wrong.  The easiest fix is probably to place the bundle in the same directory.  Pull requests welcome, or I'll get to it soon.
