### ISSUE TITLE
Timeline option disappears when refreshed

### ISSUE THREAD

**Issue by JelteF** [zepheira/exhibit3#56]
In the Nobelists demo, the button for the timeline sometimes disappears when you refresh.
The only way to get it back is by clearing the cache.

**Comment by zepheiryan** [comment]
If you're referring specifically to the one located on [databench.zepheira.com](http://databench.zepheira.com/demos/nobelists/nobelists.html), I believe that bug has been resolved by fixing extension load ordering, though the fix has not yet been published to a code server.  Please elaborate if you're talking about your own checkout or something else entirely.

**Comment by zepheiryan** [comment]
Feel free to re-open if necessary; I'm more than happy to look into a problem, though I'm fairly certain this one is already resolved.

**Comment by JelteF** [comment]
I used the code in the demos/nobelists directory to build my own widget first. That's when I encountered the problem. After that I went to the demo site to see if it was present there as well. This was the case. So if it has already been fixed could you maybe push the code to github, so it can be used in my and other's widget.

**Comment by zepheiryan** [comment]
The demos in the repository and online use an older release hosted on a code server (we have #45 sitting around at the moment to better address it).  Are you running your widget against an external code provider or against your local copy?  The fix was pushed quite a while ago.

**Comment by JelteF** [comment]
I'm running my widget against my local copy I pulled from Github.
On Jul 11, 2012 9:18 PM, "Ryan Lee" <
reply@reply.github.com>
wrote:

**Comment by zepheiryan** [comment]
As I've noted, instances of this problem that I've seen appear to have been fixed - do you think you could put up a working example of the problem you're seeing somewhere where I can look at it?  Otherwise I don't think I can reproduce it.  Thanks.
