### ISSUE TITLE
Modify create.js to use new event mechanism for autocreate

### ISSUE THREAD

**Issue by karger** [zepheira/exhibit3#60]
create.js is still used to handle autocreation of exhibits, and the way it works is to place that script after all the others.  Given the move to an event-based model, it would make sense to have autocreation (if desired) be listening for an event, as opposed to relying on some specific script ordering.  I haven't figured out enough of the event structure to decide what event it should listen for.

This has come up because I'm trying to delay execution of create.js and haven't yet found a safe event to trigger on.  I discovered that triggering on scriptsLoaded can premature, as e.g. the code in create.js relies on importers having been registered, which happens some time after scripts are loaded..

**Comment by zepheiryan** [comment]
This was on my list, and I'd be happy to see a pull request for accomplishing it.

**Comment by zepheiryan** [comment]
See #77
