### ISSUE TITLE
Nested viewPanels break

### ISSUE THREAD

**Issue by karger** [zepheira/exhibit3#71]
Not that it's likely to be a popular feature, but nested viewPanels just don't work, demonstrating that there are bugs in the viewPanel code.

**Comment by zepheiryan** [comment]
As far as I know, this has never been an explicit feature of view panels.  Feel free to submit a pull request if the feature is ever added.

**Comment by karger** [comment]
This isn't a feature request.  It's a bug report, that things break if you nest viewPanels.
