### ISSUE TITLE
Error when in nobelists demo with small dataset

### ISSUE THREAD

**Issue by JelteF** [zepheira/exhibit3#73]
When all items except the top two get removed from the JSON file, clicking one of the sort links causes this error:
Uncaught TypeError: Cannot call method 'getPluralLabel' of null                      ordered-view-frame.js:675

**Comment by zepheiryan** [comment]
There should perhaps be a more informative error, but the problem arises when you've removed any instances of properties that are listed in possibleOrders for the view (in this case, .deceased is no longer a valid order because neither of the first two items in the dataset use that property).
