### ISSUE TITLE
History system fails when underlying schema changes

### ISSUE THREAD

**Issue by karger** [zepheira/exhibit3#75]
The history system remember sort order.  If I modify the data and exhibit to remove all reference to the property that was previously used for sorting, then the history system continues to force that (now nonexistent) property to be used for the sort order.  Even worse, it breaks the sort-by link so I cannot change to a different, working sort order.

Perhaps history should be cleared if the document changes?

**Comment by karger** [comment]
At the very least there should be some mechanism for clearing the history---perhaps via an extra argument in the url

**Comment by zepheiryan** [comment]
Note there's already a mechanism for clearing history, using the developer mode of control panel presents a history clearing button.

**Comment by karger** [comment]
Of course there's a difference between a button that requires user interaction and an api call that can be used programmatically.  

Also,  reading history is good but not quite the same as clearing it---perhaps both should be available?

**Comment by zepheiryan** [comment]
Being able to clear a user's browsing history through Javascript would be a major browser security violation.
