### ISSUE TITLE
Exhibit rendering should be reversible/idempotent

### ISSUE THREAD

**Issue by karger** [zepheira/exhibit3#82]
To enhance interoperability with other tools, it would be useful if we could undo page-changes made by exhibit, or re-run the exhibit rendering code multiple times.  Exhibit is already pretty close to this, but could get all the way if we commit to the following:
1.  every dom element created dynamically by exhibit gets class "exhibit-generated" added to it
2.  exhibit should never delete dom nodes, only hide them
With these two changes, we can "unrender" any exhibit by removing all exhibit-generated items, and know that re-running exhibit configuration will produce the same result because all exhibit tags are still present.

**Comment by zepheiryan** [comment]
Your second requirement makes this a non-starter.  Browser performance degrades significantly as a DOM tree expands; that's why Exhibit works by cleaning up after itself instead of hiding and showing things.

Exhibit has a built-in history system to deal with the changes it's made.

**Comment by karger** [comment]
The second requirement is reasonable, just badly phrased.  What I meant was that exhibit should not delete any content that was part of the initial exhibit description.  Content that was created _by_ exhibit can be deleted just fine without affecting the ability to re-render.
