### ISSUE TITLE
Registry should not use dom IDs

### ISSUE THREAD

**Issue by karger** [zepheira/exhibit3#91]
Exhibit components are registered under an ID.  At present, if the dom node defining the component has an ID, that ID is used as the component ID in the registry, while if the dom node has no ID, then a fresh unique ID is generated for the component to register.

If every exhibit-defining dom node did have an ID, then registering under those IDs would be useful, as it would provide a way to find a component given its dom node.  But since we cannot guarantee that every exhibit dom node will have an ID, there is no benefit to using the dom node ID when it is present.  It simply creates inconsistency.

And it has negative side effects.  Some libraries I am currently using introduce ids on nodes that don't have them, and this leads to exhibit finding the wrong components in the registry when the exhibit is re-rendered.

**Comment by zepheiryan** [comment]
Using DOM ids provides stability and indications of author intent.  Generated registry IDs try to be stable but can change if the page changes.

Overhauling Exhibit to work with an unrelated (and unnamed) library is not a general interest feature and might be entertained in a pull request.  But probably not.
