### ISSUE TITLE
$(document).one() in event registration precludes reinitialization

### ISSUE THREAD

**Issue by karger** [zepheira/exhibit3#97]
Exhibit uses events to trigger component initialization.  Various scripts bind to an event while loading, using $(document).one("signaling event", response).  This means that it is impossible to reinitialize theses scripts, since they only listen for one occurrence of the event.  Would the be any drawback to a blanket replacement of .one() by .bind() so repeated triggerings could occur?

**Comment by karger** [comment]
Consequence: calling Exhibit.create() twice produces a nonfunctioning exhibit.

**Comment by zepheiryan** [comment]
Duplicates #92.
